version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: calendar-mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=calendar
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: calendar-backend
    depends_on:
      - mysql
    entrypoint: ["sh", "/app/wait-for.sh", "mysql:3306", "--"]
    command: ["/app/main"]
