version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: calendar-mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=calendar
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  api:
    build:
    # you can build an image repo instead of building the image locally
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: calendar-backend
    depends_on:
      - mysql
    entrypoint: ["sh", "/app/wait-for.sh", "mysql:3306", "--"]
    command: ["/app/main"]
# depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started.
# If you need to wait for a service to be ready, see Controlling startup order for more on this problem and strategies for solving it.
